class DealItem {
  const DealItem({
    required this.id,
    required this.title,
    required this.martName,
    required this.category,
    required this.price,
    required this.originalPrice,
    required this.discountRate,
    required this.imageUrl,
    required this.description,
    required this.comparisons,
    this.badge = '특가',
  });

  final String id;
  final String title;
  final String martName;
  final String category;
  final int price;
  final int originalPrice;
  final int discountRate;
  final String imageUrl;
  final String description;
  final List<MartPriceComparison> comparisons;
  final String badge;
}

class MartPriceComparison {
  const MartPriceComparison({
    required this.martName,
    required this.productName,
    required this.price,
    required this.unit,
    required this.distance,
    required this.period,
    required this.source,
    this.hasParking = true,
    this.isCheapest = false,
  });

  final String martName;
  final String productName;
  final int price;
  final String unit;
  final String distance;
  final String period;
  final String source;
  final bool hasParking;
  final bool isCheapest;
}

class FlyerItem {
  const FlyerItem({
    required this.id,
    required this.martName,
    required this.title,
    required this.period,
    required this.imageUrl,
    required this.address,
    required this.latitude,
    required this.longitude,
    required this.businessHours,
    required this.phoneNumber,
    required this.closedDays,
    required this.parkingInfo,
    required this.description,
    required this.dataSource,
    this.flyerImageUrls = const [],
  });

  final String id;
  final String martName;
  final String title;
  final String period;
  final String imageUrl;
  final String address;
  final double latitude;
  final double longitude;
  final String businessHours;
  final String phoneNumber;
  final String closedDays;
  final String parkingInfo;
  final String description;
  final String dataSource;
  final List<String> flyerImageUrls;
}

class CommunityPost {
  const CommunityPost({
    required this.title,
    required this.place,
    required this.time,
    required this.current,
    required this.capacity,
    required this.pricePerPerson,
    required this.imageUrl,
  });

  final String title;
  final String place;
  final String time;
  final int current;
  final int capacity;
  final int pricePerPerson;
  final String imageUrl;
}

class RecipeSuggestion {
  const RecipeSuggestion({
    required this.title,
    required this.reason,
    required this.time,
    required this.difficulty,
    required this.budget,
    required this.imageUrl,
    required this.ingredients,
    required this.steps,
    required this.relatedDealIds,
    this.tag = '추천',
    this.source,
    this.sourceRecipeId,
    this.license,
    this.calories,
    this.rawIngredients,
  });

  final String title;
  final String reason;
  final String time;
  final String difficulty;
  final int budget;
  final String imageUrl;
  final List<String> ingredients;
  final List<String> steps;
  final List<String> relatedDealIds;
  final String tag;
  final String? source;
  final String? sourceRecipeId;
  final String? license;
  final int? calories;
  final String? rawIngredients;

  factory RecipeSuggestion.fromJson(Map<String, dynamic> data) {
    return RecipeSuggestion(
      title: data['title'] as String? ?? '',
      reason: data['reason'] as String? ?? '공공 레시피 DB 기반 추천',
      time: data['time'] as String? ?? '20분',
      difficulty: data['difficulty'] as String? ?? '보통',
      budget: data['budget'] as int? ?? 6500,
      imageUrl: data['imageUrl'] as String? ?? '',
      ingredients: List<String>.from(data['ingredients'] as List? ?? const []),
      steps: List<String>.from(data['steps'] as List? ?? const []),
      relatedDealIds: List<String>.from(
        data['relatedDealIds'] as List? ?? const [],
      ),
      tag: data['tag'] as String? ?? '공공 레시피',
      source: data['source'] as String?,
      sourceRecipeId: data['sourceRecipeId'] as String?,
      license: data['license'] as String?,
      calories: data['calories'] as int?,
      rawIngredients: data['rawIngredients'] as String?,
    );
  }
}

class ReceiptSummary {
  const ReceiptSummary({
    required this.date,
    required this.martName,
    required this.description,
    required this.amount,
  });

  final String date;
  final String martName;
  final String description;
  final int amount;
}

const _wooriHomeMartName = '우리홈마켓 원주점';
const _wooriHomeFlyerPage1 = 'assets/flyers/woorihome_family_sale_1.jpeg';
const _wooriHomeFlyerPage2 = 'assets/flyers/woorihome_family_sale_2.jpeg';

DealItem _wooriHomeDeal({
  required String id,
  required String title,
  required String category,
  required int price,
  required String unit,
  required String period,
  required String imageUrl,
  int? originalPrice,
  String badge = '우리홈 전단',
  String description = '',
}) {
  final basePrice = originalPrice ?? price;
  final discountRate = basePrice > price
      ? (((basePrice - price) / basePrice) * 100).round()
      : 0;
  return DealItem(
    id: id,
    title: title,
    martName: _wooriHomeMartName,
    category: category,
    price: price,
    originalPrice: basePrice,
    discountRate: discountRate,
    imageUrl: imageUrl,
    description: description.isNotEmpty
        ? description
        : '우리홈마켓 상상초오월 가정의 달 특가전 전단에서 확인한 행사 상품입니다. 행사 기간과 물량은 매장 사정에 따라 달라질 수 있어요.',
    badge: badge,
    comparisons: [
      MartPriceComparison(
        martName: _wooriHomeMartName,
        productName: title,
        price: price,
        unit: unit,
        distance: '북원로',
        period: period,
        source: '전단지',
        isCheapest: true,
      ),
    ],
  );
}

final _wooriHomeFlyerDeals = [
  _wooriHomeDeal(
    id: 'woorihome-tomato-box',
    title: '완숙토마토 (5kg/1박스)',
    category: 'veg',
    price: 9900,
    unit: '5kg',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://produce',
    badge: '전기간 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-green-onion',
    title: '대파 (1단)',
    category: 'veg',
    price: 990,
    unit: '1단',
    period: '5/1 ~ 5/5',
    imageUrl: 'category://produce',
  ),
  _wooriHomeDeal(
    id: 'woorihome-potato',
    title: '하우스감자 왕특 (100g)',
    category: 'veg',
    price: 299,
    unit: '100g',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://produce',
    badge: '전기간 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-steak-sirloin',
    title: '프리미엄 등심 스테이크용 (100g)',
    category: 'meat',
    price: 2300,
    unit: '100g',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://meat',
    badge: '먹거리 플렉스',
  ),
  _wooriHomeDeal(
    id: 'woorihome-la-galbi',
    title: '최상급 LA갈비 (100g)',
    category: 'meat',
    price: 2990,
    unit: '100g',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://meat',
    badge: '먹거리 플렉스',
  ),
  _wooriHomeDeal(
    id: 'woorihome-hanwoo-bulgogi',
    title: '한우 불고기 (100g)',
    category: 'meat',
    price: 2990,
    unit: '100g',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://meat',
    badge: '먹거리 플렉스',
  ),
  _wooriHomeDeal(
    id: 'woorihome-hanwoo-grill',
    title: '한우 모듬구이 (100g)',
    category: 'meat',
    price: 8900,
    unit: '100g',
    period: '5/1 ~ 5/10',
    imageUrl: 'category://meat',
    badge: '한우 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-cherry-tomato',
    title: '스테비아 방울토마토 (4팩)',
    category: 'veg',
    price: 9900,
    unit: '4팩',
    period: '5/1 ~ 5/3',
    imageUrl: 'category://produce',
  ),
  _wooriHomeDeal(
    id: 'woorihome-melon',
    title: '고당도 참외 30상 (7개)',
    category: 'veg',
    price: 9900,
    unit: '7개',
    period: '5/1 ~ 5/3',
    imageUrl: 'category://produce',
  ),
  _wooriHomeDeal(
    id: 'woorihome-pork-belly-neck',
    title: '브랜드 냉장 삼겹살/목살 (100g)',
    category: 'meat',
    price: 1390,
    unit: '100g',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://meat',
    badge: '전기간 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-gold-kiwi',
    title: '제스프리 골드키위 (10개)',
    category: 'veg',
    price: 9900,
    unit: '10개',
    period: '5/1 ~ 5/5',
    imageUrl: 'category://produce',
  ),
  _wooriHomeDeal(
    id: 'woorihome-marinated-pork',
    title: '양념 목살 주물럭 (4근)',
    category: 'meat',
    price: 9900,
    unit: '4근',
    period: '5/1 ~ 5/5',
    imageUrl: 'category://meat',
  ),
  _wooriHomeDeal(
    id: 'woorihome-rotisserie-chicken',
    title: '우리 전기구이 통닭 (2마리)',
    category: 'processed',
    price: 9900,
    unit: '2마리',
    period: '5/4 ~ 5/5',
    imageUrl: 'category://deli',
  ),
  _wooriHomeDeal(
    id: 'woorihome-gift-melon',
    title: '선물용 참외 (5kg)',
    category: 'veg',
    price: 19900,
    unit: '5kg',
    period: '5/6 ~ 5/10',
    imageUrl: 'category://produce',
    badge: '효도데이',
  ),
  _wooriHomeDeal(
    id: 'woorihome-watermelon',
    title: '고당도 수박 (9kg 이하)',
    category: 'veg',
    price: 19900,
    unit: '9kg 이하',
    period: '5/6 ~ 5/10',
    imageUrl: 'category://produce',
    badge: '효도데이',
  ),
  _wooriHomeDeal(
    id: 'woorihome-hanwoo-bone-set',
    title: '한우 사골 선물세트 (4kg)',
    category: 'meat',
    price: 19900,
    unit: '4kg',
    period: '5/6 ~ 5/10',
    imageUrl: 'category://meat',
    badge: '효도데이',
  ),
  _wooriHomeDeal(
    id: 'woorihome-sungsimdang-cake',
    title: '성심당st 망고생크림케이크 2호',
    category: 'processed',
    price: 39900,
    unit: '2호',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://bakery',
    badge: '베이커리',
  ),
  _wooriHomeDeal(
    id: 'woorihome-sungsimdang-roll',
    title: '성심당st 순수롤케이크',
    category: 'processed',
    price: 14900,
    unit: '1개',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://bakery',
    badge: '베이커리',
  ),
  _wooriHomeDeal(
    id: 'woorihome-carnation',
    title: '생화 카네이션 화분 (1호/2호)',
    category: 'living',
    price: 9900,
    originalPrice: 25000,
    unit: '1개',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://gift',
    badge: '가정의 달',
  ),
  _wooriHomeDeal(
    id: 'woorihome-water',
    title: '고운샘물 무라벨 (2L/6입)',
    category: 'processed',
    price: 1700,
    unit: '2L x 6',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://processed',
    badge: '전기간 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-yonggari-nugget',
    title: '하림 용가리치킨 + 치킨너겟 (300g+300g)',
    category: 'processed',
    price: 4990,
    unit: '600g',
    period: '5/4 ~ 5/5',
    imageUrl: 'category://deli',
  ),
  _wooriHomeDeal(
    id: 'woorihome-asahi',
    title: '롯데 아사히 캔 (500ml/6캔)',
    category: 'processed',
    price: 9900,
    unit: '6캔',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://processed',
    badge: '전기간 특가',
  ),
  _wooriHomeDeal(
    id: 'woorihome-snack-pick',
    title: '롯데/오리온/해태/크라운 과자 골라담기 (15개)',
    category: 'processed',
    price: 9900,
    unit: '15개',
    period: '5/4 ~ 5/5',
    imageUrl: 'category://processed',
  ),
  _wooriHomeDeal(
    id: 'woorihome-mini-tonkatsu',
    title: '굿프렌즈 미니돈까스 (1kg)',
    category: 'processed',
    price: 2990,
    unit: '1kg',
    period: '5/1 ~ 5/14',
    imageUrl: 'category://meat',
  ),
  _wooriHomeDeal(
    id: 'woorihome-shin-ramyun',
    title: '신라면 (5입)',
    category: 'processed',
    price: 2990,
    unit: '5입',
    period: '5/1 ~ 5/3',
    imageUrl: 'category://processed',
  ),
  _wooriHomeDeal(
    id: 'woorihome-fruit-drink',
    title: '해태 과일촌 망고복숭아/감귤자몽 (1.5L)',
    category: 'processed',
    price: 990,
    unit: '1.5L',
    period: '5/1 ~ 5/3',
    imageUrl: 'category://processed',
  ),
  _wooriHomeDeal(
    id: 'woorihome-maxim',
    title: '맥심 모카골드 (160T+20T)',
    category: 'processed',
    price: 21900,
    unit: '180T',
    period: '5/1 ~ 5/3',
    imageUrl: 'category://processed',
  ),
  _wooriHomeDeal(
    id: 'woorihome-red-ginseng-stick',
    title: '홍삼진 이뮨스틱 (30일)',
    category: 'processed',
    price: 19900,
    unit: '30일',
    period: '5/6 ~ 5/10',
    imageUrl: 'category://gift',
    badge: '효도데이',
  ),
];

// 임시 목업 이미지입니다. 출시 전에는 마트 제공/직접 촬영/승인 이미지로 교체합니다.
final dealItems = [
  ..._wooriHomeFlyerDeals,
  DealItem(
    id: 'hanwoo',
    title: '프리미엄 한우 세트 (1kg)',
    martName: '행복한식자재마트 단구점',
    category: 'meat',
    price: 110000,
    originalPrice: 150000,
    discountRate: 27,
    imageUrl:
        'https://sitem.ssgcdn.com/98/64/64/item/1000043646498_i1_1200.jpg',
    description:
        '최상급 품질의 한우를 엄선해 구성한 프리미엄 세트입니다. 명절 선물이나 특별한 날 가족 식탁에 어울리는 행사 상품입니다.',
    badge: '전국단위 특가',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재마트 단구점',
        productName: '프리미엄 한우 세트 (1kg)',
        price: 110000,
        unit: '1kg',
        distance: '1.2km',
        period: '4/28 ~ 5/04',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '무항생제 한우 선물세트 (1kg)',
        price: 125000,
        unit: '1kg',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '관리자 입력',
      ),
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '1등급 한우 모듬 세트 (1.2kg)',
        price: 132000,
        unit: '1.2kg',
        distance: '4.6km',
        period: '4/28 ~ 5/02',
        source: '온라인 전단',
      ),
    ],
  ),
  DealItem(
    id: 'egg',
    title: '동물복지 유정란 (30구)',
    martName: '행복한식자재마트 단구점',
    category: 'meat',
    price: 6900,
    originalPrice: 12800,
    discountRate: 46,
    imageUrl:
        'https://sitem.ssgcdn.com/07/25/58/item/1000608582507_i1_1200.jpg',
    description:
        '넓은 사육환경에서 생산된 동물복지 유정란입니다. 30구 대용량 구성이라 가족 장보기와 식당 준비에 모두 적합합니다.',
    badge: '행복 식자재',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재마트 단구점',
        productName: '동물복지 유정란 (30구)',
        price: 6900,
        unit: '30구',
        distance: '1.2km',
        period: '4/28 ~ 5/04',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '친환경 유정란 (30구)',
        price: 8500,
        unit: '30구',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '영수증 특가 제보',
      ),
      MartPriceComparison(
        martName: '우리홈마켓 원주점',
        productName: '무항생제 유정란 대란 30구',
        price: 9200,
        unit: '30구',
        distance: '배송',
        period: '오늘 도착',
        source: '온라인 특가 정보',
        hasParking: false,
      ),
    ],
  ),
  DealItem(
    id: 'strawberry',
    title: '제철 딸기 (500g)',
    martName: '하나로마트 판부농협본점',
    category: 'veg',
    price: 7900,
    originalPrice: 10500,
    discountRate: 25,
    imageUrl:
        'https://sitem.ssgcdn.com/79/38/46/item/1000038463879_i1_1200.jpg',
    description: '당도 높은 제철 딸기 500g 행사 상품입니다. 아이 간식이나 디저트 재료로 쓰기 좋습니다.',
    badge: '신선 과일',
    comparisons: [
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '제철 딸기 (500g)',
        price: 7900,
        unit: '500g',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '행복한식자재마트 단구점',
        productName: '논산 딸기 특품 (500g)',
        price: 8900,
        unit: '500g',
        distance: '1.2km',
        period: '4/28 ~ 5/04',
        source: '매장 특가 제보',
      ),
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '새벽수확 딸기 (500g)',
        price: 9500,
        unit: '500g',
        distance: '4.6km',
        period: '4/28 ~ 5/02',
        source: '온라인 전단',
      ),
    ],
  ),
  DealItem(
    id: 'oil',
    title: '대용량 식용유 (1.8L)',
    martName: '대륙식자재마트 원주본점',
    category: 'processed',
    price: 4200,
    originalPrice: 6000,
    discountRate: 30,
    imageUrl:
        'https://sitem.ssgcdn.com/24/11/61/item/0000006611124_i1_1200.jpg',
    description:
        '튀김, 볶음, 전 요리에 두루 쓰기 좋은 1.8L 식용유 행사 상품입니다. 대용량 장보기 품목으로 추천합니다.',
    badge: '대용량 특가',
    comparisons: [
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '대용량 식용유 (1.8L)',
        price: 4200,
        unit: '1.8L',
        distance: '3.1km',
        period: '4/28 ~ 5/07',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '상지식자재할인마트',
        productName: '식용유 (1.8L)',
        price: 4900,
        unit: '1.8L',
        distance: '2.4km',
        period: '4/28 ~ 5/03',
        source: '매장 특가 제보',
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '카놀라유 (1.8L)',
        price: 5500,
        unit: '1.8L',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '영수증 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'onion',
    title: '양파 (15kg/망)',
    martName: '상지식자재할인마트',
    category: 'veg',
    price: 12000,
    originalPrice: 20000,
    discountRate: 40,
    imageUrl:
        'https://sitem.ssgcdn.com/97/16/63/item/1000012631697_i1_1200.jpg',
    description: '소분모임과 식당 장보기에 적합한 15kg 양파망입니다. 김치, 카레, 볶음요리 준비에 실속 있는 구성입니다.',
    badge: '박스특가',
    comparisons: [
      MartPriceComparison(
        martName: '상지식자재할인마트',
        productName: '양파 (15kg/망)',
        price: 12000,
        unit: '15kg',
        distance: '2.4km',
        period: '4/28 ~ 5/03',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '양파 대용량망 (15kg)',
        price: 13500,
        unit: '15kg',
        distance: '3.1km',
        period: '4/28 ~ 5/07',
        source: '관리자 입력',
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '양파 (15kg)',
        price: 15800,
        unit: '15kg',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'pork_front',
    title: '국내산 돼지 앞다리살 (1kg)',
    martName: '대륙식자재마트 원주본점',
    category: 'meat',
    price: 8900,
    originalPrice: 12900,
    discountRate: 31,
    imageUrl:
        'https://sitem.ssgcdn.com/84/10/98/item/1000520981084_i1_1200.jpg',
    description: '제육볶음, 수육, 찌개용으로 활용하기 좋은 국내산 돼지 앞다리살 1kg 행사 상품입니다.',
    badge: '정육 특가',
    comparisons: [
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '국내산 돼지 앞다리살 (1kg)',
        price: 8900,
        unit: '1kg',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '돼지 앞다리살 불고기용 (1kg)',
        price: 9800,
        unit: '1kg',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '매장 특가 제보',
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '국내산 앞다리살 (1kg)',
        price: 10900,
        unit: '1kg',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '영수증 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'chicken_breast',
    title: '닭가슴살 냉장팩 (1kg)',
    martName: '엘마트 개운점',
    category: 'meat',
    price: 6500,
    originalPrice: 8900,
    discountRate: 27,
    imageUrl:
        'https://sitem.ssgcdn.com/80/39/85/item/1000019853980_i1_1200.jpg',
    description: '샐러드, 볶음밥, 다이어트 도시락에 활용하기 좋은 냉장 닭가슴살 1kg 상품입니다.',
    badge: '단백질 특가',
    comparisons: [
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '닭가슴살 냉장팩 (1kg)',
        price: 6500,
        unit: '1kg',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '닭가슴살 벌크팩 (1kg)',
        price: 7200,
        unit: '1kg',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '전단지',
      ),
    ],
  ),
  DealItem(
    id: 'tofu',
    title: '국산콩 두부 (300g x 2입)',
    martName: '행복한식자재마트 문막점',
    category: 'processed',
    price: 2500,
    originalPrice: 3600,
    discountRate: 31,
    imageUrl:
        'https://sitem.ssgcdn.com/05/01/57/item/1000621570105_i1_1200.jpg',
    description: '찌개, 부침, 샐러드에 두루 쓰기 좋은 국산콩 두부 2입 묶음 행사 상품입니다.',
    badge: '반찬 재료',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재마트 문막점',
        productName: '국산콩 두부 (300g x 2입)',
        price: 2500,
        unit: '2입',
        distance: '문막',
        period: '4/29 ~ 5/04',
        source: '매장 특가 제보',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '부침두부 (300g x 2입)',
        price: 2900,
        unit: '2입',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '영수증 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'milk_1l',
    title: '맛있는 우유 (900ml)',
    martName: '엘마트 개운점',
    category: 'dairy',
    price: 1980,
    originalPrice: 2850,
    discountRate: 31,
    imageUrl:
        'https://sitem.ssgcdn.com/02/86/45/item/1000348458602_i1_1200.jpg',
    description: '아침 식사와 간식에 곁들이기 좋은 900ml 우유 행사 상품입니다.',
    badge: '유제품 특가',
    comparisons: [
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '맛있는 우유 (900ml)',
        price: 1980,
        unit: '900ml',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '서울우유 (1L)',
        price: 2850,
        unit: '1L',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '영수증 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'yogurt',
    title: '떠먹는 요구르트 플레인 (8입)',
    martName: 'SG마트 단계점',
    category: 'dairy',
    price: 3980,
    originalPrice: 5200,
    discountRate: 23,
    imageUrl:
        'https://sitem.ssgcdn.com/14/28/92/item/1000327922814_i1_1200.jpg',
    description: '아침 대용이나 아이 간식으로 좋은 플레인 요구르트 8입 묶음 상품입니다.',
    badge: '간식 특가',
    comparisons: [
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '떠먹는 요구르트 플레인 (8입)',
        price: 3980,
        unit: '8입',
        distance: '4.0km',
        period: '4/29 ~ 5/02',
        source: '온라인 전단',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '플레인 요구르트 (8입)',
        price: 4500,
        unit: '8입',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'apple',
    title: '세척 사과 (5입 봉)',
    martName: '하나로마트 판부농협본점',
    category: 'veg',
    price: 6900,
    originalPrice: 9900,
    discountRate: 30,
    imageUrl:
        'https://sitem.ssgcdn.com/05/72/64/item/1000546647205_i1_1200.jpg',
    description: '아침 과일이나 도시락 간식으로 좋은 세척 사과 5입 봉 상품입니다.',
    badge: '과일 특가',
    comparisons: [
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '세척 사과 (5입 봉)',
        price: 6900,
        unit: '5입',
        distance: '2.8km',
        period: '4/29 ~ 5/01',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '국산 사과 (5입)',
        price: 7900,
        unit: '5입',
        distance: '4.0km',
        period: '4/29 ~ 5/02',
        source: '온라인 전단',
      ),
    ],
  ),
  DealItem(
    id: 'potato',
    title: '감자 (3kg 박스)',
    martName: '대륙식자재마트 원주본점',
    category: 'veg',
    price: 5900,
    originalPrice: 8500,
    discountRate: 31,
    imageUrl:
        'https://sitem.ssgcdn.com/79/02/14/item/1000206140279_i1_1200.jpg',
    description: '카레, 조림, 볶음 요리에 활용하기 좋은 감자 3kg 박스 행사 상품입니다.',
    badge: '박스특가',
    comparisons: [
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '감자 (3kg 박스)',
        price: 5900,
        unit: '3kg',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '상지식자재할인마트',
        productName: '감자 실속팩 (3kg)',
        price: 6800,
        unit: '3kg',
        distance: '확인 필요',
        period: '4/29 ~ 5/03',
        source: '관리자 입력',
      ),
    ],
  ),
  DealItem(
    id: 'rice_10kg',
    title: '철원 오대쌀 (10kg)',
    martName: 'SG마트 단계점',
    category: 'rice',
    price: 32900,
    originalPrice: 38900,
    discountRate: 15,
    imageUrl:
        'https://sitem.ssgcdn.com/47/91/70/item/0000007709147_i1_1200.jpg',
    description: '밥맛 좋은 쌀을 찾는 가정에 적합한 10kg 쌀 행사 상품입니다.',
    badge: '쌀 특가',
    comparisons: [
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '철원 오대쌀 (10kg)',
        price: 32900,
        unit: '10kg',
        distance: '4.0km',
        period: '4/29 ~ 5/02',
        source: '온라인 전단',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '국산 쌀 (10kg)',
        price: 34500,
        unit: '10kg',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'ramen',
    title: '신라면 멀티팩 (5입)',
    martName: '엘마트 개운점',
    category: 'processed',
    price: 3800,
    originalPrice: 4500,
    discountRate: 16,
    imageUrl:
        'https://sitem.ssgcdn.com/48/36/33/item/0000008333648_i1_1200.jpg',
    description: '간편식으로 많이 찾는 라면 5입 멀티팩 행사 상품입니다.',
    badge: '라면 특가',
    comparisons: [
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '신라면 멀티팩 (5입)',
        price: 3800,
        unit: '5입',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '신라면 (5입)',
        price: 4100,
        unit: '5입',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'tuna',
    title: '참치캔 (150g x 4입)',
    martName: '행복한식자재마트 문막점',
    category: 'processed',
    price: 7900,
    originalPrice: 10500,
    discountRate: 25,
    imageUrl:
        'https://sitem.ssgcdn.com/25/06/38/item/0000008380625_i1_1200.jpg',
    description: '김치찌개, 주먹밥, 샐러드에 활용하기 좋은 참치캔 4입 묶음입니다.',
    badge: '통조림 특가',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재마트 문막점',
        productName: '참치캔 (150g x 4입)',
        price: 7900,
        unit: '4입',
        distance: '문막',
        period: '4/29 ~ 5/04',
        source: '매장 특가 제보',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '참치 살코기 (150g x 4입)',
        price: 8900,
        unit: '4입',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '영수증 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'soy_sauce',
    title: '진간장 (1.7L)',
    martName: '대륙식자재마트 원주본점',
    category: 'seasoning',
    price: 3900,
    originalPrice: 5200,
    discountRate: 25,
    imageUrl:
        'https://sitem.ssgcdn.com/70/29/70/item/1000599702970_i1_1200.jpg',
    description: '볶음, 조림, 무침에 자주 쓰이는 기본 조미료 진간장 1.7L 행사 상품입니다.',
    badge: '조미료 특가',
    comparisons: [
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '진간장 (1.7L)',
        price: 3900,
        unit: '1.7L',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '양조간장 (1.7L)',
        price: 4600,
        unit: '1.7L',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'gochujang',
    title: '태양초 고추장 (1kg)',
    martName: '엘마트 개운점',
    category: 'seasoning',
    price: 6900,
    originalPrice: 8900,
    discountRate: 22,
    imageUrl:
        'https://sitem.ssgcdn.com/12/00/61/item/0000006610012_i1_1200.jpg',
    description: '비빔밥, 볶음, 찌개 양념에 활용하기 좋은 고추장 1kg 행사 상품입니다.',
    badge: '양념 특가',
    comparisons: [
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '태양초 고추장 (1kg)',
        price: 6900,
        unit: '1kg',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '매운 고추장 (1kg)',
        price: 7500,
        unit: '1kg',
        distance: '3.1km',
        period: '4/29 ~ 5/05',
        source: '관리자 입력',
      ),
    ],
  ),
  DealItem(
    id: 'detergent',
    title: '주방세제 리필 (1.2L)',
    martName: '엘마트 개운점',
    category: 'living',
    price: 2900,
    originalPrice: 4200,
    discountRate: 31,
    imageUrl:
        'https://sitem.ssgcdn.com/85/00/46/item/2097001460085_i1_1200.jpg',
    description: '매일 쓰는 주방세제를 실속 있게 구매할 수 있는 리필형 생활용품 행사 상품입니다.',
    badge: '생활용품',
    comparisons: [
      MartPriceComparison(
        martName: '엘마트 개운점',
        productName: '주방세제 리필 (1.2L)',
        price: 2900,
        unit: '1.2L',
        distance: '2.0km',
        period: '4/29 ~ 5/03',
        source: '전단지',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '행복한식자재마트 문막점',
        productName: '주방세제 대용량 리필 (1.2L)',
        price: 3400,
        unit: '1.2L',
        distance: '문막',
        period: '4/29 ~ 5/04',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'bean_sprouts',
    title: '국산 콩나물 (1kg)',
    martName: '행복한식자재마트 태장점',
    category: 'veg',
    price: 1900,
    originalPrice: 2800,
    discountRate: 32,
    imageUrl:
        'https://sitem.ssgcdn.com/36/65/38/item/1000532386536_i1_1200.jpg',
    description: '국, 무침, 볶음요리에 두루 쓰기 좋은 1kg 콩나물 특가 상품입니다.',
    badge: '태장점 특가',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재마트 태장점',
        productName: '국산 콩나물 (1kg)',
        price: 1900,
        unit: '1kg',
        distance: '태장동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '행복한식자재마트 단구점',
        productName: '콩나물 실속팩 (1kg)',
        price: 2200,
        unit: '1kg',
        distance: '단구동',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'frozen_dumpling',
    title: '왕만두 냉동팩 (1.4kg)',
    martName: '행복한식자재할인마트 태장점',
    category: 'processed',
    price: 8900,
    originalPrice: 11900,
    discountRate: 25,
    imageUrl:
        'https://sitem.ssgcdn.com/53/20/75/item/1000544752053_i1_1200.jpg',
    description: '찜, 국, 전골에 활용하기 좋은 대용량 왕만두 냉동팩입니다.',
    badge: '할인형 특가',
    comparisons: [
      MartPriceComparison(
        martName: '행복한식자재할인마트 태장점',
        productName: '왕만두 냉동팩 (1.4kg)',
        price: 8900,
        unit: '1.4kg',
        distance: '태장동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '우리홈마켓 원주점',
        productName: '냉동 만두 대용량 (1.2kg)',
        price: 9900,
        unit: '1.2kg',
        distance: '태장동',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'monomart_sauce',
    title: '업소용 돈까스소스 (2kg)',
    martName: '모노마트 원주점',
    category: 'seasoning',
    price: 9800,
    originalPrice: 12500,
    discountRate: 22,
    imageUrl:
        'https://sitem.ssgcdn.com/77/19/38/item/1000577381977_i1_1200.jpg',
    description: '분식, 도시락, 튀김 메뉴에 쓰기 좋은 업소용 소스 특가 상품입니다.',
    badge: '업소용 특가',
    comparisons: [
      MartPriceComparison(
        martName: '모노마트 원주점',
        productName: '업소용 돈까스소스 (2kg)',
        price: 9800,
        unit: '2kg',
        distance: '단계동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '대륙식자재마트 원주본점',
        productName: '돈까스소스 대용량 (2kg)',
        price: 10900,
        unit: '2kg',
        distance: '개운동',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'sparkling_water',
    title: '탄산수 묶음 (500ml x 20입)',
    martName: '우리홈마켓 원주점',
    category: 'processed',
    price: 9900,
    originalPrice: 13900,
    discountRate: 29,
    imageUrl:
        'https://sitem.ssgcdn.com/39/52/57/item/1000054575239_i1_1200.jpg',
    description: '24시간 마트에서 장보기 좋은 탄산수 20입 묶음 특가입니다.',
    badge: '24시간 특가',
    comparisons: [
      MartPriceComparison(
        martName: '우리홈마켓 원주점',
        productName: '탄산수 묶음 (500ml x 20입)',
        price: 9900,
        unit: '20입',
        distance: '태장동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: 'SG마트 행구점',
        productName: '탄산수 500ml 묶음',
        price: 11500,
        unit: '20입',
        distance: '행구동',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'salad_mix',
    title: '샐러드 채소 믹스 (500g)',
    martName: '오드리푸드마켓 원주점',
    category: 'veg',
    price: 4900,
    originalPrice: 6900,
    discountRate: 29,
    imageUrl:
        'https://sitem.ssgcdn.com/46/83/78/item/1000633788346_i1_1200.jpg',
    description: '간편하게 씻어 먹기 좋은 샐러드 채소 믹스 특가 상품입니다.',
    badge: '신선 특가',
    comparisons: [
      MartPriceComparison(
        martName: '오드리푸드마켓 원주점',
        productName: '샐러드 채소 믹스 (500g)',
        price: 4900,
        unit: '500g',
        distance: '태장동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '하나로마트 판부농협본점',
        productName: '쌈채소 믹스팩 (500g)',
        price: 5900,
        unit: '500g',
        distance: '관설동',
        period: '이번 주',
        source: '전단지',
      ),
    ],
  ),
  DealItem(
    id: 'flour_bulk',
    title: '중력 밀가루 (10kg)',
    martName: '탑식자재할인마트',
    category: 'processed',
    price: 13900,
    originalPrice: 16900,
    discountRate: 18,
    imageUrl:
        'https://sitem.ssgcdn.com/68/90/60/item/0000006609068_i1_1200.jpg',
    description: '전, 부침, 베이킹에 활용하기 좋은 10kg 대용량 밀가루입니다.',
    badge: '문막 특가',
    comparisons: [
      MartPriceComparison(
        martName: '탑식자재할인마트',
        productName: '중력 밀가루 (10kg)',
        price: 13900,
        unit: '10kg',
        distance: '문막읍',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: '행복한식자재마트 문막점',
        productName: '밀가루 대용량 (10kg)',
        price: 14800,
        unit: '10kg',
        distance: '문막읍',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
  DealItem(
    id: 'grape_pack',
    title: '씨없는 포도 (1.5kg)',
    martName: 'SG마트 행구점',
    category: 'veg',
    price: 11900,
    originalPrice: 15900,
    discountRate: 25,
    imageUrl:
        'https://sitem.ssgcdn.com/53/24/29/item/1000633292453_i1_1200.jpg',
    description: '아이 간식과 디저트로 좋은 씨없는 포도 1.5kg 특가 상품입니다.',
    badge: '행구점 특가',
    comparisons: [
      MartPriceComparison(
        martName: 'SG마트 행구점',
        productName: '씨없는 포도 (1.5kg)',
        price: 11900,
        unit: '1.5kg',
        distance: '행구동',
        period: '이번 주',
        source: '관리자 입력',
        isCheapest: true,
      ),
      MartPriceComparison(
        martName: 'SG마트 단계점',
        productName: '수입 포도팩 (1.5kg)',
        price: 12900,
        unit: '1.5kg',
        distance: '단계동',
        period: '이번 주',
        source: '매장 특가 제보',
      ),
    ],
  ),
];

const flyerItems = [
  FlyerItem(
    id: 'daeryuk-wonju',
    martName: '대륙식자재마트 원주본점',
    title: '24시간 운영 대형 식자재마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
    address: '강원 원주시 서원대로 411',
    latitude: 37.3303007369883,
    longitude: 127.950960743815,
    businessHours: '24시간 (연중무휴)',
    phoneNumber: '033-764-4945',
    closedDays: '연중무휴',
    parkingInfo: '주차 정보 확인 필요',
    description: '개운동 서원대로에 위치한 대형 식자재마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'happy-dangu',
    martName: '행복한식자재마트 단구점',
    title: '단구권 지역형 식자재마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80',
    address: '강원 원주시 남원로534번길 64-1',
    latitude: 37.3277032604811,
    longitude: 127.952717323244,
    businessHours: '07:00~22:00',
    phoneNumber: '033-765-7737',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '단구동 생활권에서 이용하기 좋은 지역형 식자재마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'happy-taejang',
    martName: '행복한식자재마트 태장점',
    title: '태장동 행복한식자재마트 지점',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    address: '강원 원주시 현충로 12',
    latitude: 37.3569,
    longitude: 127.9549,
    businessHours: '07:00~22:00',
    phoneNumber: '033-744-9600',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '태장동 현충로에 위치한 행복한식자재마트 지점입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'happy-discount-taejang',
    martName: '행복한식자재할인마트 태장점',
    title: '태장동 할인형 식자재마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
    address: '강원 원주시 현충로 305',
    latitude: 37.3806563319568,
    longitude: 127.947552772827,
    businessHours: '07:00~22:30',
    phoneNumber: '033-743-1030',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '태장동 현충로에 위치한 할인형 식자재마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'happy-munmak',
    martName: '행복한식자재마트 문막점',
    title: '문막읍 외곽 지역 식자재마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80',
    address: '강원 원주시 문막읍 건등로 62 1층',
    latitude: 37.3147389767589,
    longitude: 127.822601487375,
    businessHours: '08:00~22:00',
    phoneNumber: '033-744-1008',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '문막읍 건등로에 위치한 행복한식자재마트 외곽 지역 매장입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'sangji-food',
    martName: '상지식자재할인마트',
    title: '우산동 대표 식자재마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    address: '강원 원주시 북원로 2501',
    latitude: 37.3708,
    longitude: 127.9399,
    businessHours: '06:00~23:00',
    phoneNumber: '033-733-5400',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '북원로에 위치한 원주 대표 식자재마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'hanaro-panbu',
    martName: '하나로마트 판부농협본점',
    title: '농협 운영 신선식품 강점 마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=800&q=80',
    address: '강원 원주시 치악로 1527 판부농협',
    latitude: 37.3202105,
    longitude: 127.9648052,
    businessHours: '동절기 08:00~21:00 / 하절기 08:00~22:00',
    phoneNumber: '033-769-0200',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '판부농협에서 운영하는 하나로마트 본점으로 신선식품 장보기에 적합합니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'lmart-gaeun',
    martName: '엘마트 개운점',
    title: '개운동 일반마트 + 식자재',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
    address: '강원 원주시 단구로 227',
    latitude: 37.3334,
    longitude: 127.9517,
    businessHours: '07:00~22:30',
    phoneNumber: '0507-1424-2523',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '개운동 단구로에 위치한 일반마트와 식자재 장보기 매장입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'monomart-wonju',
    martName: '모노마트 원주점',
    title: '단계동 업소용 식자재 매장',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80',
    address: '강원 원주시 서원대로 121-9 1층',
    latitude: 37.3469676193714,
    longitude: 127.927832482842,
    businessHours: '09:00~19:00',
    phoneNumber: '033-735-0429',
    closedDays: '일요일 휴무',
    parkingInfo: '주차 정보 확인 필요',
    description: '단계동 서원대로에 위치한 업소용 성격의 식자재 매장입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'woorihome-wonju',
    martName: '우리홈마켓 원주점',
    title: '상상초오월 가정의 달 특가전 1탄',
    period: '5/1 ~ 5/14',
    imageUrl: _wooriHomeFlyerPage1,
    address: '강원 원주시 북원로 2638 1층 우리홈마켓',
    latitude: 37.3787706,
    longitude: 127.9468679,
    businessHours: '24시간 영업, 일요일 22:00 마감, 월요일 08:00 오픈',
    phoneNumber: '033-744-5515',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description:
        '북원로에 위치한 24시간 운영 마트입니다. 상상초오월 가정의 달 특가전 전단 기준으로 신선식품, 정육, 가공식품 행사 상품을 반영했습니다.',
    dataSource: '사용자 제공 전단지',
    flyerImageUrls: [_wooriHomeFlyerPage1, _wooriHomeFlyerPage2],
  ),
  FlyerItem(
    id: 'odri-food',
    martName: '오드리푸드마켓 원주점',
    title: '태장동 식자재 + 일반식품 마켓',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=800&q=80',
    address: '강원 원주시 현충로 54',
    latitude: 37.3605,
    longitude: 127.9559,
    businessHours: '08:00~22:00',
    phoneNumber: '0507-1345-8200',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '태장동 현충로에 위치한 식자재와 일반식품을 함께 취급하는 마켓입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'sg-dangye',
    martName: 'SG마트 단계점',
    title: '단계동 동네형 마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
    address: '강원 원주시 백간길 25',
    latitude: 37.3520827,
    longitude: 127.9263005,
    businessHours: '08:00~22:00',
    phoneNumber: '0507-1428-6672',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '단계동 백간길에 위치한 동네형 마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'top-food-munmak',
    martName: '탑식자재할인마트',
    title: '문막읍 식자재 할인마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80',
    address: '강원 원주시 문막읍 원문로 1587',
    latitude: 37.3207425474695,
    longitude: 127.833485536996,
    businessHours: '정보 없음',
    phoneNumber: '033-734-1066',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '문막읍 원문로에 위치한 식자재 할인마트입니다.',
    dataSource: '기본 정보',
  ),
  FlyerItem(
    id: 'sg-haenggu',
    martName: 'SG마트 행구점',
    title: '행구동 동네형 마트',
    period: '마트 정보',
    imageUrl:
        'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    address: '강원 원주시 행구로 148',
    latitude: 37.3417148743283,
    longitude: 127.972513317756,
    businessHours: '08:00~22:00',
    phoneNumber: '033-733-8811',
    closedDays: '확인 필요',
    parkingInfo: '주차 정보 확인 필요',
    description: '행구동 행구로에 위치한 SG마트 지점입니다.',
    dataSource: '기본 정보',
  ),
];

const communityPosts = [
  CommunityPost(
    title: '대용량 양파 1망 소분해요',
    place: '원주 중앙공원 인근',
    time: '오늘 18:00',
    current: 2,
    capacity: 4,
    pricePerPerson: 1500,
    imageUrl:
        'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&q=80',
  ),
  CommunityPost(
    title: '맛있는 우유 900ml 1개',
    place: '상지마트 앞',
    time: '오늘 19:30',
    current: 1,
    capacity: 1,
    pricePerPerson: 1600,
    imageUrl:
        'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80',
  ),
];

const recipeSuggestions = [
  RecipeSuggestion(
    title: '1만원 이하 제육볶음',
    reason: '돼지고기 특가 + 보유 양파 활용',
    time: '20분',
    difficulty: '쉬움',
    budget: 9200,
    imageUrl:
        'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=800&q=80',
    ingredients: ['돼지고기', '양파', '대파', '고춧가루', '간장', '설탕', '식용유'],
    steps: [
      '돼지고기는 먹기 좋은 크기로 썰고 양파와 대파를 준비합니다.',
      '고춧가루, 간장, 설탕을 섞어 양념장을 만듭니다.',
      '팬에 식용유를 두르고 돼지고기를 먼저 볶습니다.',
      '양파와 대파, 양념장을 넣고 센 불에서 빠르게 볶아 마무리합니다.',
    ],
    relatedDealIds: ['pork_front', 'onion', 'soy_sauce', 'oil'],
    tag: '돼지고기 특가',
  ),
  RecipeSuggestion(
    title: '계란 대파 볶음밥',
    reason: '계란 특가 + 기본 조미료 활용',
    time: '15분',
    difficulty: '쉬움',
    budget: 4800,
    imageUrl:
        'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    ingredients: ['계란', '대파', '밥', '소금', '간장', '식용유'],
    steps: [
      '대파를 잘게 썰고 계란은 소금 약간을 넣어 풀어둡니다.',
      '팬에 식용유를 두르고 대파를 볶아 향을 냅니다.',
      '계란을 넣어 반쯤 익힌 뒤 밥을 넣고 고슬하게 볶습니다.',
      '간장으로 간을 맞추고 센 불에서 한 번 더 볶아냅니다.',
    ],
    relatedDealIds: ['egg', 'soy_sauce', 'oil'],
    tag: '냉장고 비우기',
  ),
  RecipeSuggestion(
    title: '양파 듬뿍 카레',
    reason: '대용량 양파 소분 + 감자 특가 조합',
    time: '35분',
    difficulty: '보통',
    budget: 7800,
    imageUrl:
        'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    ingredients: ['양파', '감자', '당근', '카레가루', '식용유', '밥'],
    steps: [
      '양파, 감자, 당근을 한입 크기로 썰어 준비합니다.',
      '냄비에 식용유를 두르고 양파를 충분히 볶아 단맛을 냅니다.',
      '감자와 당근을 넣고 볶은 뒤 물을 부어 익힙니다.',
      '카레가루를 풀어 넣고 농도가 날 때까지 끓인 뒤 밥과 함께 냅니다.',
    ],
    relatedDealIds: ['onion', 'potato', 'oil'],
    tag: '양파 특가',
  ),
  RecipeSuggestion(
    title: '두부 고추장조림',
    reason: '두부 특가와 기본 양념으로 만드는 밥반찬',
    time: '18분',
    difficulty: '쉬움',
    budget: 5600,
    imageUrl:
        'https://images.unsplash.com/photo-1593357849627-cbbc9fda6b05?w=800&q=80',
    ingredients: ['두부', '양파', '대파', '고추장', '간장', '설탕', '식용유'],
    steps: [
      '두부는 물기를 빼고 도톰하게 썰어 팬에 노릇하게 굽습니다.',
      '고추장, 간장, 설탕, 물을 섞어 조림 양념을 만듭니다.',
      '양파와 대파를 넣고 양념을 부어 중약불에서 졸입니다.',
      '양념이 자작해지면 두부에 끼얹어가며 마무리합니다.',
    ],
    relatedDealIds: ['tofu', 'gochujang', 'onion'],
    tag: '두부 특가',
  ),
  RecipeSuggestion(
    title: '콩나물 김치국',
    reason: '김치와 콩나물만 있으면 빠르게 끓이는 국물 메뉴',
    time: '20분',
    difficulty: '쉬움',
    budget: 3900,
    imageUrl:
        'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    ingredients: ['김치', '콩나물', '대파', '고춧가루', '간장', '다진마늘'],
    steps: [
      '김치는 먹기 좋게 썰고 콩나물은 씻어 준비합니다.',
      '냄비에 물을 붓고 김치와 고춧가루를 넣어 먼저 끓입니다.',
      '콩나물과 다진마늘을 넣고 뚜껑을 덮어 익힙니다.',
      '대파와 간장으로 간을 맞춰 마무리합니다.',
    ],
    relatedDealIds: ['bean_sprouts'],
    tag: '국물 추천',
  ),
  RecipeSuggestion(
    title: '참치 김치볶음밥',
    reason: '참치캔과 김치, 밥으로 만드는 빠른 한 끼',
    time: '15분',
    difficulty: '쉬움',
    budget: 6200,
    imageUrl:
        'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    ingredients: ['참치', '김치', '밥', '계란', '대파', '참기름', '식용유'],
    steps: [
      '김치와 대파를 잘게 썰고 참치는 기름을 가볍게 뺍니다.',
      '팬에 식용유를 두르고 대파와 김치를 먼저 볶습니다.',
      '참치와 밥을 넣고 고슬하게 볶은 뒤 참기름을 더합니다.',
      '계란 프라이를 올리면 든든한 한 끼가 됩니다.',
    ],
    relatedDealIds: ['tuna', 'egg'],
    tag: '15분 한 끼',
  ),
  RecipeSuggestion(
    title: '닭가슴살 샐러드볼',
    reason: '닭가슴살과 샐러드채소로 가볍게 먹는 저녁',
    time: '12분',
    difficulty: '쉬움',
    budget: 7400,
    imageUrl:
        'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
    ingredients: ['닭가슴살', '샐러드채소', '계란', '요거트', '소금'],
    steps: [
      '닭가슴살은 데우거나 팬에 구워 한입 크기로 자릅니다.',
      '계란은 삶거나 프라이로 준비합니다.',
      '샐러드채소 위에 닭가슴살과 계란을 올립니다.',
      '요거트에 소금 약간을 섞어 가벼운 드레싱으로 곁들입니다.',
    ],
    relatedDealIds: ['chicken_breast', 'salad_mix', 'yogurt', 'egg'],
    tag: '가벼운 메뉴',
  ),
  RecipeSuggestion(
    title: '감자채 계란전',
    reason: '감자와 계란으로 만드는 저렴한 부침 메뉴',
    time: '22분',
    difficulty: '보통',
    budget: 5200,
    imageUrl:
        'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=800&q=80',
    ingredients: ['감자', '계란', '양파', '소금', '식용유'],
    steps: [
      '감자와 양파를 얇게 채 썰어 소금으로 가볍게 간합니다.',
      '계란을 풀어 감자채와 섞습니다.',
      '팬에 식용유를 두르고 얇게 펼쳐 앞뒤로 부칩니다.',
      '겉은 바삭하고 속은 촉촉할 때 접시에 담습니다.',
    ],
    relatedDealIds: ['potato', 'egg', 'onion'],
    tag: '감자 특가',
  ),
  RecipeSuggestion(
    title: '만두 라면전골',
    reason: '라면과 냉동만두로 든든하게 끓이는 가성비 전골',
    time: '18분',
    difficulty: '쉬움',
    budget: 6800,
    imageUrl:
        'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    ingredients: ['라면', '만두', '대파', '양파', '고춧가루', '계란'],
    steps: [
      '냄비에 물을 붓고 라면스프와 고춧가루를 넣어 끓입니다.',
      '만두, 양파, 대파를 넣고 먼저 익힙니다.',
      '라면을 넣고 면이 풀어질 때까지 끓입니다.',
      '마지막에 계란을 넣어 취향에 맞게 익힙니다.',
    ],
    relatedDealIds: ['ramen', 'frozen_dumpling', 'egg'],
    tag: '분식 특가',
  ),
  RecipeSuggestion(
    title: '사과 요거트볼',
    reason: '사과와 요거트로 만드는 간단한 아침/간식',
    time: '7분',
    difficulty: '아주 쉬움',
    budget: 4500,
    imageUrl:
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    ingredients: ['사과', '요거트', '설탕'],
    steps: [
      '사과는 깨끗이 씻어 먹기 좋은 크기로 썹니다.',
      '그릇에 요거트를 담고 사과를 올립니다.',
      '단맛이 부족하면 설탕을 아주 조금 더합니다.',
      '차갑게 먹으면 아침 대용이나 간식으로 좋습니다.',
    ],
    relatedDealIds: ['apple', 'yogurt'],
    tag: '간식 추천',
  ),
  RecipeSuggestion(
    title: '우유 감자수프',
    reason: '감자와 우유로 부드럽게 만드는 아침 수프',
    time: '25분',
    difficulty: '보통',
    budget: 6400,
    imageUrl:
        'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    ingredients: ['감자', '우유', '양파', '소금', '식용유'],
    steps: [
      '감자와 양파를 얇게 썰어 준비합니다.',
      '냄비에 식용유를 두르고 양파를 투명해질 때까지 볶습니다.',
      '감자와 물을 넣고 부드러워질 때까지 끓입니다.',
      '우유를 넣고 약불에서 데운 뒤 소금으로 간합니다.',
    ],
    relatedDealIds: ['potato', 'milk_1l', 'onion'],
    tag: '부드러운 메뉴',
  ),
  RecipeSuggestion(
    title: '돼지고기 된장찌개',
    reason: '돼지고기와 두부를 넣어 든든하게 끓이는 찌개',
    time: '30분',
    difficulty: '보통',
    budget: 8800,
    imageUrl:
        'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80',
    ingredients: ['돼지고기', '두부', '양파', '대파', '된장', '다진마늘'],
    steps: [
      '돼지고기와 양파, 대파, 두부를 먹기 좋게 준비합니다.',
      '냄비에 물을 끓이고 된장을 풀어 국물 맛을 냅니다.',
      '돼지고기와 양파를 넣어 익힌 뒤 두부를 넣습니다.',
      '다진마늘과 대파를 넣고 한소끔 더 끓입니다.',
    ],
    relatedDealIds: ['pork_front', 'tofu', 'onion'],
    tag: '찌개 추천',
  ),
  RecipeSuggestion(
    title: '밀가루 부추 없는 간장수제비',
    reason: '밀가루와 기본 양념으로 만드는 초간단 국물식',
    time: '28분',
    difficulty: '보통',
    budget: 3600,
    imageUrl:
        'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    ingredients: ['밀가루', '간장', '대파', '다진마늘', '소금'],
    steps: [
      '밀가루에 물과 소금을 조금씩 넣어 말랑한 반죽을 만듭니다.',
      '냄비에 물을 끓이고 간장과 다진마늘로 국물 간을 합니다.',
      '반죽을 얇게 떼어 넣고 익을 때까지 끓입니다.',
      '대파를 넣고 부족한 간은 소금으로 맞춥니다.',
    ],
    relatedDealIds: ['flour_bulk', 'soy_sauce'],
    tag: '초저가 메뉴',
  ),
];

const receiptSummaries = [
  ReceiptSummary(
    date: '4.28',
    martName: '행복한식자재마트 단구점',
    description: '계란 외 4건',
    amount: 24500,
  ),
  ReceiptSummary(
    date: '4.24',
    martName: '하나로마트 판부농협본점',
    description: '돼지고기 앞다리살 외 2건',
    amount: 18200,
  ),
];
