// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxWmrNC2Gj934894_V4-UNe4-ZFbFR-U',
    appId: '1:123049771054:web:8e48aa039bb7034ae8dfbf',
    messagingSenderId: '123049771054',
    projectId: 'wonju-mart-app-1018',
    authDomain: 'wonju-mart-app-1018.firebaseapp.com',
    storageBucket: 'wonju-mart-app-1018.firebasestorage.app',
    measurementId: 'G-P8W8XFFDXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqz3p6pZGQ5ZufZ1zhWhXDLVxk4vbMD8s',
    appId: '1:123049771054:android:87bcaacb005a1430e8dfbf',
    messagingSenderId: '123049771054',
    projectId: 'wonju-mart-app-1018',
    storageBucket: 'wonju-mart-app-1018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv3B3SIqPyA2kdt_2fmf6tzuOBW3Divm0',
    appId: '1:123049771054:ios:40fa88cf54c7a8fce8dfbf',
    messagingSenderId: '123049771054',
    projectId: 'wonju-mart-app-1018',
    storageBucket: 'wonju-mart-app-1018.firebasestorage.app',
    iosBundleId: 'com.wonjumart.app',
  );
}
